#!/bin/bash

#SBATCH --partition=med
#SBATCH --nodes=1
#SBATCH --time=6:30:00
#SBATCH --cpus-per-task=20
#SBATCH --mem-per-cpu=2100
#SBATCH --job-name=parallel_mpc_1
#SBATCH --output=/work/smtakhan/parallel_1.out.txt
#SBATCH --mail-type=ALL
#SBATCH --mail-user=taimoor.khan@tu-dortmund.de

cd /home/smtakhan
module purge
source taimoor_master_thesis_2/bin/activate
cd ~/Modular_submission_mshaped_high1_with_changes_multistage
srun python sampling_1.py

